# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

#워크플로우 수행할 이벤트 작성
#main 브랜치를 대상으로 pull request 생성 시 수행됨
 on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

#jobs는 수행할 워크플로우
#어떤 일을 실행할 지 작성하는 부분
jobs:
  #아래 build는 job 이름으로 아무거나 써도 됨
  build:
    #runs-on : job을 실행할 깃허브 CI서버 OS  << runner라고 부르는 듯
    runs-on: ubuntu-latest

    #steps는 밑으로 하나씩 처리할 일을 순서대로 작성
    steps:
    # 1) 워크플로우 실행 전 기본적으로 체크아웃 필요
    #깃허브액션과 연결된 repo 코드를 runner로 옮기는 것
    - uses: actions/checkout@v3
    # 2) JDK 11 버전 설치, 다른 JDK 버전을 사용한다면 수정 필요
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    # 3) Gradle 사용. arguments 를 붙이면 뒤에 그대로 실행된다고 생각하면 됨
    # 이 워크플로우는 gradle clean build 를 수행함
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean build
